# Generated by Django 3.2.5 on 2021-07-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='Black', max_length=50)),
                ('ram', models.CharField(default='2 GB', max_length=50)),
                ('price', models.IntegerField(default=10000)),
            ],
        ),
    ]
